### ISSUE TITLE
Need Font Awesome-style icon for Codewars

### ISSUE THREAD

**Issue by stevehopkinson** [FAC9/nomastew-blog#6]
Codewars doesn't currently have a Font Awesome-style icon. Some people have made SVG alternatives, such as here: http://www.eagle-js.com/social-coding

**Comment by msachi** [comment]
Svg for Codewars icon added

**Comment by msachi** [comment]
Still need to make all social icons the same size & reorder them so they're the same order on the main and personal pages

**Comment by stevehopkinson** [comment]
Online tool to convert in-line HTML svg to .svg files: http://www.hiqpdf.com/demo/ConvertHtmlToSvg.aspx

**Comment by stevehopkinson** [comment]
You need to do some fiddling around to match your browser width/height to the svg viewport size, or it ends up displaying at the wrong scale. But you should be able to find that in the main HTML svg tag.
